name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
deployers = [
  "0xca111279D6aeEc39849ed5CD2bA3045381643422"
]

[setting.salt]
defaultValue = "owned-greeter"

[contract.Greeter]
artifact = "src/Greeter.sol:Greeter"
salt = "<%= settings.salt %>"

[contract.ExampleContract]
artifact = "src/ExampleContract.sol:ExampleContract"
salt = "<%= settings.salt %>"
