name = "owned-greeter"
version = "0.0.4"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
deployers = ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]
preset = "clone-d"

[clone.greeter]
source = "owned-greeter:latest@main"
target = "owned-greeter:0.0.1@clone-clone-d"
options.salt = "owned-greeter-clone-d"
